import pandas as pd

themes = [
# 1. Bases & définitions (5)
{"id":1,"cluster":"Bases & définitions","titre":"Assurance emprunteur : définition, rôle et fonctionnement","mot_cle_principal":"assurance emprunteur définition fonctionnement","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Expliquer garanties DC, PTIA, IPT, ITT et le parcours général."},
{"id":2,"cluster":"Bases & définitions","titre":"Quelles garanties sont réellement obligatoires pour un prêt immobilier ?","mot_cle_principal":"garanties obligatoires prêt immobilier assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Rester générique, rappeler que les exigences varient selon prêteur et projet."},
{"id":3,"cluster":"Bases & définitions","titre":"Qu’est-ce que la quotité d’assurance ? Comment la choisir à deux","mot_cle_principal":"quotité assurance emprunteur couple","intention":"informationnelle","type_evergreen":"guide","notes":"Inclure exemples 50/50, 70/30, 100/100 et impacts sur la prime."},
{"id":4,"cluster":"Bases & définitions","titre":"Carence, franchise, exclusions : les délais qui changent vos indemnisations","mot_cle_principal":"délai de carence franchise exclusions assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Définir clairement carence vs franchise; exemples simples."},
{"id":5,"cluster":"Bases & définitions","titre":"Capital restant dû vs indemnisation forfaitaire : quelles différences ?","mot_cle_principal":"assurance emprunteur capital restant dû vs forfaitaire","intention":"investigation commerciale","type_evergreen":"comparaison","notes":"Comparer scénarios d’indemnisation; éviter chiffres non sourcés."},

# 2. Prix & devis (5)
{"id":6,"cluster":"Prix & devis","titre":"Comment est calculé le coût de l’assurance emprunteur ?","mot_cle_principal":"calcul coût assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Facteurs: âge, santé, fumeur, métier, durée, capital."},
{"id":7,"cluster":"Prix & devis","titre":"Taux d’assurance : sur capital initial ou capital restant dû ?","mot_cle_principal":"taux assurance emprunteur capital initial ou restant dû","intention":"informationnelle","type_evergreen":"comparaison","notes":"Expliquer mode de calcul et effet sur coût total."},
{"id":8,"cluster":"Prix & devis","titre":"Simulation : l’impact d’un changement d’assureur sur le coût total","mot_cle_principal":"changer assurance emprunteur économies simulation","intention":"investigation commerciale","type_evergreen":"guide","notes":"Scénarios génériques; insister sur équivalence de garanties."},
{"id":9,"cluster":"Prix & devis","titre":"Fumeur vs non‑fumeur : quel impact sur la prime ?","mot_cle_principal":"assurance emprunteur fumeur impact prime","intention":"informationnelle","type_evergreen":"comparaison","notes":"Définir critères fumeur/non‑fumeur; éviter % non sourcés."},
{"id":10,"cluster":"Prix & devis","titre":"Âge et durée de prêt : comment influencent‑ils votre tarif ?","mot_cle_principal":"âge durée prêt impact tarif assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Explications pédagogiques sans promesses absolues."},

# 3. Santé & questionnaire (5)
{"id":11,"cluster":"Santé & questionnaire","titre":"Questionnaire de santé : que doit‑on déclarer (et comment) ?","mot_cle_principal":"questionnaire santé assurance emprunteur déclaration","intention":"informationnelle","type_evergreen":"guide","notes":"Transparence, exactitude; rappeler confidentialité des données."},
{"id":12,"cluster":"Santé & questionnaire","titre":"Droit à l’oubli : ce que change la loi pour les anciens malades","mot_cle_principal":"droit à l’oubli assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Rester général; indiquer que conditions peuvent évoluer."},
{"id":13,"cluster":"Santé & questionnaire","titre":"Surprime et exclusions médicales : comprendre les réponses de l’assureur","mot_cle_principal":"surprime exclusions médicales assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Expliquer logique de tarification et de sélection du risque."},
{"id":14,"cluster":"Santé & questionnaire","titre":"Assurance emprunteur sans questionnaire de santé : dans quels cas ?","mot_cle_principal":"assurance emprunteur sans questionnaire de santé conditions","intention":"investigation commerciale","type_evergreen":"guide","notes":"Préciser que critères d’éligibilité existent; pas de promesse."},
{"id":15,"cluster":"Santé & questionnaire","titre":"Arrêt de travail, invalidité : comment l’assureur évalue le risque","mot_cle_principal":"évaluation risque arrêt de travail invalidité assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Rester pédagogique, sans conseils médicaux."},

# 4. Garanties (5)
{"id":16,"cluster":"Garanties","titre":"Garanties DC, PTIA, IPT, ITT : décryptage complet","mot_cle_principal":"garanties dc ptia ipt itt assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Définitions claires et conditions habituelles."},
{"id":17,"cluster":"Garanties","titre":"Incapacité temporaire de travail (ITT) : indemnisation et limites","mot_cle_principal":"assurance emprunteur itt indemnisation limites","intention":"informationnelle","type_evergreen":"guide","notes":"Expliquer franchise, durée d’indemnisation, reprises partielles."},
{"id":18,"cluster":"Garanties","titre":"Invalidité permanente (IPT/IPP) : comment ça marche ?","mot_cle_principal":"assurance emprunteur ipt ipp fonctionnement","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Taux d’invalidité, consolidation; pas de seuils chiffrés non sourcés."},
{"id":19,"cluster":"Garanties","titre":"Perte d’emploi : garantie utile ou gadget ?","mot_cle_principal":"assurance emprunteur perte d’emploi utilité","intention":"investigation commerciale","type_evergreen":"décision","notes":"Lister limites fréquentes; prudence sur conditions variables."},
{"id":20,"cluster":"Garanties","titre":"Indemnisation forfaitaire vs indemnitaire : ce qui change pour vous","mot_cle_principal":"indemnisation forfaitaire vs indemnitaire assurance emprunteur","intention":"informationnelle","type_evergreen":"comparaison","notes":"Pros/cons selon profils; rester neutre."},

# 5. Délégation d’assurance (5)
{"id":21,"cluster":"Délégation d’assurance","titre":"Délégation d’assurance : pourquoi la banque n’est pas votre seule option","mot_cle_principal":"délégation d’assurance emprunteur banque alternative","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Introduire le principe sans citer de banques."},
{"id":22,"cluster":"Délégation d’assurance","titre":"Équivalence de garanties : la clé d’une délégation acceptée","mot_cle_principal":"équivalence de garanties assurance emprunteur","intention":"informationnelle","type_evergreen":"guide","notes":"Expliquer critères et méthode de comparaison."},
{"id":23,"cluster":"Délégation d’assurance","titre":"Dossier de délégation : pièces à fournir et étapes","mot_cle_principal":"dossier délégation assurance emprunteur pièces étapes","intention":"informationnelle","type_evergreen":"checklist","notes":"Lister pièces courantes; rappeler que banques peuvent compléter."},
{"id":24,"cluster":"Délégation d’assurance","titre":"Changer d’assurance après l’offre de prêt : est‑ce vraiment possible ?","mot_cle_principal":"changer assurance emprunteur après offre de prêt","intention":"informationnelle","type_evergreen":"guide","notes":"Rester générique sur les règles; pas de délais juridiques précis."},
{"id":25,"cluster":"Délégation d’assurance","titre":"Banque vs assureur externe : comparaison sur garanties et prix","mot_cle_principal":"banque vs assureur externe assurance emprunteur","intention":"investigation commerciale","type_evergreen":"comparaison","notes":"Comparer approche, flexibilité, coût potentiel."},

# 6. Changer & résilier (5)
{"id":26,"cluster":"Changer & résilier","titre":"Résilier son assurance emprunteur : mode d’emploi clair","mot_cle_principal":"résilier assurance emprunteur mode d’emploi","intention":"informationnelle","type_evergreen":"guide","notes":"Étapes générales, rester prudent sur délais légaux."},
{"id":27,"cluster":"Changer & résilier","titre":"Lettre de résiliation : modèle, pièces et erreurs à éviter","mot_cle_principal":"modèle lettre résiliation assurance emprunteur","intention":"transactionnelle","type_evergreen":"checklist","notes":"Proposer une trame générique et conseils pratiques."},
{"id":28,"cluster":"Changer & résilier","titre":"Calendrier pour changer d’assurance : quand s’y prendre ?","mot_cle_principal":"quand changer assurance emprunteur calendrier","intention":"informationnelle","type_evergreen":"guide","notes":"Repères temporels génériques, sans citer d’échéances légales."},
{"id":29,"cluster":"Changer & résilier","titre":"Refus de la banque : comment réagir et faire valoir l’équivalence","mot_cle_principal":"refus banque délégation assurance emprunteur équivalence","intention":"informationnelle","type_evergreen":"guide","notes":"Conseils de communication; mentionner médiation de manière générale."},
{"id":30,"cluster":"Changer & résilier","titre":"Suivre sa résiliation : preuves, délais et bonnes pratiques","mot_cle_principal":"suivre résiliation assurance emprunteur preuves délais","intention":"informationnelle","type_evergreen":"checklist","notes":"Accusés de réception, sauvegarde des échanges."},

# 7. Immobilier & prêts (5)
{"id":31,"cluster":"Immobilier & prêts","titre":"Prêt relais : particularités côté assurance emprunteur","mot_cle_principal":"assurance emprunteur prêt relais particularités","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Spécificités de durée et de capital."},
{"id":32,"cluster":"Immobilier & prêts","titre":"Investissement locatif : points clés pour l’assurance emprunteur","mot_cle_principal":"assurance emprunteur investissement locatif points clés","intention":"informationnelle","type_evergreen":"guide","notes":"Rester neutre sur fiscalité; focus garanties."},
{"id":33,"cluster":"Immobilier & prêts","titre":"SCI : assurance des co‑emprunteurs et quotités adaptées","mot_cle_principal":"assurance emprunteur sci quotité coemprunteurs","intention":"informationnelle","type_evergreen":"guide","notes":"Spécificités de répartition du risque."},
{"id":34,"cluster":"Immobilier & prêts","titre":"Primo‑accédant : construire une couverture efficace et abordable","mot_cle_principal":"assurance emprunteur primo accédant conseils","intention":"investigation commerciale","type_evergreen":"guide","notes":"Sensibiliser aux garanties essentielles sans survente."},
{"id":35,"cluster":"Immobilier & prêts","titre":"PTZ et assurance emprunteur : règles pratiques à connaître","mot_cle_principal":"ptz assurance emprunteur règles pratiques","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Rester générique, pas de réglementation détaillée."},

# 8. Optimisation & conseils (5)
{"id":36,"cluster":"Optimisation & conseils","titre":"Choisir la bonne quotité à deux emprunteurs : stratégies concrètes","mot_cle_principal":"choisir quotité assurance emprunteur à deux","intention":"investigation commerciale","type_evergreen":"guide","notes":"Exemples de répartition selon revenus et patrimoine."},
{"id":37,"cluster":"Optimisation & conseils","titre":"Réduire le coût sans réduire la protection : 7 leviers efficaces","mot_cle_principal":"réduire coût assurance emprunteur leviers","intention":"informationnelle","type_evergreen":"liste","notes":"Délégation, ajustement garanties, durée, prévention."},
{"id":38,"cluster":"Optimisation & conseils","titre":"Quand augmenter sa couverture a du sens","mot_cle_principal":"augmenter couverture assurance emprunteur quand","intention":"informationnelle","type_evergreen":"décision","notes":"Naissance, revenus, risque pro; rester prudent."},
{"id":39,"cluster":"Optimisation & conseils","titre":"Mettre à jour son contrat après un événement de vie","mot_cle_principal":"mettre à jour contrat assurance emprunteur événement de vie","intention":"informationnelle","type_evergreen":"guide","notes":"Mariage, séparation, déménagement, changement d’emploi."},
{"id":40,"cluster":"Optimisation & conseils","titre":"Travailleurs non‑salariés : anticiper le risque professionnel","mot_cle_principal":"assurance emprunteur tns risque professionnel","intention":"informationnelle","type_evergreen":"guide","notes":"Adapter ITT/IPT; preuves de revenus."},

# 9. Profils & métiers (5)
{"id":41,"cluster":"Profils & métiers","titre":"Fonctionnaires : spécificités utiles côté assurance emprunteur","mot_cle_principal":"assurance emprunteur fonctionnaire spécificités","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Stabilité d’emploi, garanties à calibrer."},
{"id":42,"cluster":"Profils & métiers","titre":"Indépendants et dirigeants : quelles garanties prioriser ?","mot_cle_principal":"assurance emprunteur indépendant dirigeant garanties","intention":"informationnelle","type_evergreen":"guide","notes":"Focus ITT/IPP et justificatifs."},
{"id":43,"cluster":"Profils & métiers","titre":"Professions à risques : attentes courantes des assureurs","mot_cle_principal":"assurance emprunteur professions à risques attentes","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Déclaration d’activités spécifiques."},
{"id":44,"cluster":"Profils & métiers","titre":"Jeunes emprunteurs vs seniors : adapter sa couverture","mot_cle_principal":"assurance emprunteur jeunes vs seniors couverture","intention":"informationnelle","type_evergreen":"comparaison","notes":"Restrictions d’âge possibles; rester général."},
{"id":45,"cluster":"Profils & métiers","titre":"Emprunteurs expatriés ou revenus à l’étranger : cas particuliers","mot_cle_principal":"assurance emprunteur expatrié cas particulier","intention":"informationnelle","type_evergreen":"guide","notes":"Vérifier pays de résidence, couverture internationale."},

# 10. Sports & loisirs (5)
{"id":46,"cluster":"Sports & loisirs","titre":"Sports à risques et exclusions : comment se couvrir","mot_cle_principal":"assurance emprunteur sports à risques exclusions","intention":"informationnelle","type_evergreen":"guide","notes":"Lister sports souvent exclus; options possibles."},
{"id":47,"cluster":"Sports & loisirs","titre":"Plongée, alpinisme, sports mécaniques : déclarations indispensables","mot_cle_principal":"assurance emprunteur sports mécaniques alpinisme plongée","intention":"informationnelle","type_evergreen":"checklist","notes":"Certificats, fréquence, niveau de pratique."},
{"id":48,"cluster":"Sports & loisirs","titre":"Missions et séjours à l’étranger : quels impacts sur ITT/IPT ?","mot_cle_principal":"missions à l’étranger impact itt ipt assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Préciser que conditions varient selon contrat."},
{"id":49,"cluster":"Sports & loisirs","titre":"Pratique amateur vs professionnelle : ce qui change pour l’assureur","mot_cle_principal":"assurance emprunteur sport amateur vs pro","intention":"informationnelle","type_evergreen":"comparaison","notes":"Différences de risque; déclaration honnête."},
{"id":50,"cluster":"Sports & loisirs","titre":"Attestations et certificats sportifs : constituer un dossier solide","mot_cle_principal":"attestation certificat sport assurance emprunteur","intention":"transactionnelle","type_evergreen":"checklist","notes":"Rassembler documents utiles en amont."},

# 11. Sinistre & gestion (5)
{"id":51,"cluster":"Sinistre & gestion","titre":"Déclarer un sinistre ITT/IPT : la check‑list complète","mot_cle_principal":"déclarer sinistre itt ipt assurance emprunteur checklist","intention":"transactionnelle","type_evergreen":"checklist","notes":"Pièces, délais indicatifs, interlocuteurs."},
{"id":52,"cluster":"Sinistre & gestion","titre":"Franchise et délais : éviter les mauvaises surprises","mot_cle_principal":"franchise délais sinistre assurance emprunteur","intention":"informationnelle","type_evergreen":"guide","notes":"Expliquer période non indemnisée; exemples pédagogiques."},
{"id":53,"cluster":"Sinistre & gestion","titre":"Reprise partielle du travail : effet sur l’indemnisation","mot_cle_principal":"reprise partielle travail effet indemnisation assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Scénarios courants; rester générique."},
{"id":54,"cluster":"Sinistre & gestion","titre":"Consolidation médicale et taux d’invalidité : étapes clés","mot_cle_principal":"consolidation médicale taux invalidité assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Processus général; pas de seuils chiffrés."},
{"id":55,"cluster":"Sinistre & gestion","titre":"Refus d’indemnisation : comment contester sereinement","mot_cle_principal":"refus indemnisation assurance emprunteur recours","intention":"informationnelle","type_evergreen":"guide","notes":"Étapes d’escalade, mentionner médiation sans détailler le droit."},

# 12. Financement & TAEG (5)
{"id":56,"cluster":"Financement & TAEG","titre":"Assurance emprunteur et TAEG : ce qui entre dans le calcul","mot_cle_principal":"assurance emprunteur taeg calcul","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Pédagogie sur composantes du coût du crédit."},
{"id":57,"cluster":"Financement & TAEG","titre":"Comprendre le taux d’assurance vs taux d’intérêt du prêt","mot_cle_principal":"taux assurance vs taux prêt immobilier","intention":"informationnelle","type_evergreen":"comparaison","notes":"Ne pas confondre; expliquer interactions."},
{"id":58,"cluster":"Financement & TAEG","titre":"Coût mensuel vs coût total : bien lire son échéancier","mot_cle_principal":"coût mensuel vs coût total assurance emprunteur","intention":"informationnelle","type_evergreen":"guide","notes":"Exemples d’échéanciers; pédagogie simple."},
{"id":59,"cluster":"Financement & TAEG","titre":"Taux d’usure et assurance : comprendre les interactions","mot_cle_principal":"taux d’usure et assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Explications générales; rappeler que seuils évoluent."},
{"id":60,"cluster":"Financement & TAEG","titre":"Assurance sur capital initial vs sur CRD : avantages et limites","mot_cle_principal":"assurance capital initial vs capital restant dû","intention":"investigation commerciale","type_evergreen":"comparaison","notes":"Mettre en avant effet sur coût total et cash‑flow."},

# 13. Souscription & parcours client (5)
{"id":61,"cluster":"Souscription & parcours","titre":"Du devis à l’adhésion : les étapes d’une souscription réussie","mot_cle_principal":"étapes souscription assurance emprunteur","intention":"informationnelle","type_evergreen":"guide","notes":"Parcours type; rôles banque/assureur/courtier."},
{"id":62,"cluster":"Souscription & parcours","titre":"Documents à préparer pour aller vite","mot_cle_principal":"documents souscription assurance emprunteur liste","intention":"transactionnelle","type_evergreen":"checklist","notes":"Pièces d’identité, prêt, santé selon cas."},
{"id":63,"cluster":"Souscription & parcours","titre":"Sélection médicale : télé‑interview, examens, délais","mot_cle_principal":"sélection médicale assurance emprunteur téléinterview examens","intention":"informationnelle","type_evergreen":"guide","notes":"Décrire processus sans promettre d’issue."},
{"id":64,"cluster":"Souscription & parcours","titre":"Couverture temporaire en attente de décision : comment ça marche","mot_cle_principal":"couverture temporaire attente décision assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Conditions fréquentes et limites."},
{"id":65,"cluster":"Souscription & parcours","titre":"Souscrire en ligne en toute sécurité : bonnes pratiques","mot_cle_principal":"souscrire assurance emprunteur en ligne sécurité","intention":"informationnelle","type_evergreen":"guide","notes":"Vérifier identité du site, CGV, mentions légales."},

# 14. Cas familiaux (5)
{"id":66,"cluster":"Cas familiaux","titre":"Deux revenus inégaux : quelle quotité choisir intelligemment ?","mot_cle_principal":"quotité assurance emprunteur revenus inégaux","intention":"investigation commerciale","type_evergreen":"guide","notes":"Exemples d’allocation alignée sur revenus/charges."},
{"id":67,"cluster":"Cas familiaux","titre":"Concubinage, PACS, mariage : impacts sur l’assurance emprunteur","mot_cle_principal":"assurance emprunteur concubinage pacs mariage","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Rester général; conseils de coordination juridique."},
{"id":68,"cluster":"Cas familiaux","titre":"Co‑emprunteur non assuré : risques et alternatives","mot_cle_principal":"coemprunteur non assuré risques assurance emprunteur","intention":"informationnelle","type_evergreen":"décision","notes":"Expliquer exposition financière et solutions."},
{"id":69,"cluster":"Cas familiaux","titre":"Famille monoparentale : quelles priorités de garanties ?","mot_cle_principal":"assurance emprunteur famille monoparentale garanties","intention":"informationnelle","type_evergreen":"guide","notes":"Focus sur maintien de la capacité de remboursement."},
{"id":70,"cluster":"Cas familiaux","titre":"Garantie croisée vs individuelle : quel montage choisir ?","mot_cle_principal":"garantie croisée vs individuelle assurance emprunteur","intention":"investigation commerciale","type_evergreen":"comparaison","notes":"Comparer risques croisés et budget."},

# 15. Rachat & renégociation (5)
{"id":71,"cluster":"Rachat & renégociation","titre":"Rachat de crédit : faut‑il revoir son assurance ?","mot_cle_principal":"rachat de crédit assurance emprunteur revoir","intention":"informationnelle","type_evergreen":"décision","notes":"Mettre à jour garanties et quotités."},
{"id":72,"cluster":"Rachat & renégociation","titre":"Renégocier le prêt : l’opportunité de changer d’assurance","mot_cle_principal":"renégociation prêt changer assurance emprunteur","intention":"informationnelle","type_evergreen":"guide","notes":"Synchroniser calendrier et documents."},
{"id":73,"cluster":"Rachat & renégociation","titre":"Allonger ou réduire la durée : effets sur la couverture","mot_cle_principal":"modifier durée prêt effet assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Lien entre durée, coût et garanties."},
{"id":74,"cluster":"Rachat & renégociation","titre":"Regrouper plusieurs prêts : comment consolider sa protection","mot_cle_principal":"regroupement de crédits assurance emprunteur","intention":"informationnelle","type_evergreen":"guide","notes":"Vérifier cohérence des garanties post‑regroupement."},
{"id":75,"cluster":"Rachat & renégociation","titre":"Remboursement anticipé : quels impacts sur l’assurance ?","mot_cle_principal":"remboursement anticipé impact assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Préciser effets possibles sur primes et garanties."},

# 16. Conformité & réglementation (5)
{"id":76,"cluster":"Conformité & réglementation","titre":"Fiche standardisée d’information (FSI) : savoir la lire","mot_cle_principal":"fiche standardisée information fsi assurance emprunteur","intention":"informationnelle","type_evergreen":"guide","notes":"Expliquer rubriques clés pour comparer."},
{"id":77,"cluster":"Conformité & réglementation","titre":"Équivalence de garanties : méthode pratique de comparaison","mot_cle_principal":"méthode équivalence garanties assurance emprunteur","intention":"transactionnelle","type_evergreen":"checklist","notes":"Tableau de critères; rester générique juridiquement."},
{"id":78,"cluster":"Conformité & réglementation","titre":"Convention AERAS : accéder au crédit avec un risque de santé","mot_cle_principal":"convention aeras assurance emprunteur explications","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Rester général; rappeler que conditions évoluent."},
{"id":79,"cluster":"Conformité & réglementation","titre":"Données médicales : comment sont‑elles protégées ?","mot_cle_principal":"protection données médicales assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Parler confidentialité et minimisation des données."},
{"id":80,"cluster":"Conformité & réglementation","titre":"Publicité et comparateurs : lire entre les lignes","mot_cle_principal":"publicité comparateur assurance emprunteur conseils","intention":"informationnelle","type_evergreen":"guide","notes":"Repérer clauses, exclusions, limites de garanties."},

# 17. Comparatifs & choix (5)
{"id":81,"cluster":"Comparatifs & choix","titre":"Banque vs assureur externe : qui convient à votre profil ?","mot_cle_principal":"comparatif banque assureur externe assurance emprunteur","intention":"investigation commerciale","type_evergreen":"comparaison","notes":"Aider à choisir selon profil et besoins."},
{"id":82,"cluster":"Comparatifs & choix","titre":"Forfaitaire vs indemnitaire : quelle logique privilégier ?","mot_cle_principal":"forfaitaire vs indemnitaire assurance emprunteur choix","intention":"informationnelle","type_evergreen":"comparaison","notes":"Prendre en compte profession et revenus."},
{"id":83,"cluster":"Comparatifs & choix","titre":"Trois profils, trois contrats : étude de cas pédagogique","mot_cle_principal":"étude de cas assurance emprunteur profils contrats","intention":"informationnelle","type_evergreen":"étude de cas","notes":"Cas génériques anonymisés; pas de chiffres précis."},
{"id":84,"cluster":"Comparatifs & choix","titre":"Top erreurs à éviter quand on compare deux offres","mot_cle_principal":"erreurs comparaison offres assurance emprunteur","intention":"informationnelle","type_evergreen":"liste","notes":"Équivalence, exclusions, franchises, garanties optionnelles."},
{"id":85,"cluster":"Comparatifs & choix","titre":"Tableau de lecture : 10 critères pour juger une garantie","mot_cle_principal":"critères comparaison garantie assurance emprunteur","intention":"transactionnelle","type_evergreen":"checklist","notes":"Donner un canevas réutilisable."},

# 18. Patrimoine & montage (5)
{"id":86,"cluster":"Patrimoine & montage","titre":"Investisseur locatif : points de vigilance côté assurance","mot_cle_principal":"investisseur locatif points vigilance assurance emprunteur","intention":"informationnelle","type_evergreen":"guide","notes":"Coordonner couverture et stratégie locative."},
{"id":87,"cluster":"Patrimoine & montage","titre":"SCI à l’IS ou à l’IR : incidences à connaître (sans conseil fiscal)","mot_cle_principal":"sci is ir assurance emprunteur incidences","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Rester très général; renvoyer vers conseil pro pour fiscalité."},
{"id":88,"cluster":"Patrimoine & montage","titre":"Prêt in fine : spécificités d’assurance emprunteur","mot_cle_principal":"assurance emprunteur prêt in fine spécificités","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Focus sur capital remboursé en fin de prêt."},
{"id":89,"cluster":"Patrimoine & montage","titre":"Nantissement, hypothèque : y a‑t‑il un impact sur l’assurance ?","mot_cle_principal":"nantissement hypothèque impact assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Expliquer liens sans se substituer au conseil juridique."},
{"id":90,"cluster":"Patrimoine & montage","titre":"Transmission et assurance emprunteur : bonnes pratiques","mot_cle_principal":"transmission succession assurance emprunteur bonnes pratiques","intention":"informationnelle","type_evergreen":"guide","notes":"Coordonner bénéficiaires/contrats; rester prudent juridiquement."},

# 19. Expérience & service (5)
{"id":91,"cluster":"Expérience & service","titre":"Service client : à quoi s’attendre avec un assureur emprunteur","mot_cle_principal":"service client assurance emprunteur attentes","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Délais, canaux, qualité de suivi."},
{"id":92,"cluster":"Expérience & service","titre":"Accélérer la souscription : 6 astuces qui font gagner du temps","mot_cle_principal":"accélérer souscription assurance emprunteur astuces","intention":"transactionnelle","type_evergreen":"liste","notes":"Préparer pièces, répondre vite, canal digital."},
{"id":93,"cluster":"Expérience & service","titre":"Médiation et réclamations : comment ça fonctionne","mot_cle_principal":"médiation réclamation assurance emprunteur fonctionnement","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Processus général; contacts types."},
{"id":94,"cluster":"Expérience & service","titre":"Être accompagné en cas de sinistre : les bons réflexes","mot_cle_principal":"accompagnement sinistre assurance emprunteur réflexes","intention":"informationnelle","type_evergreen":"guide","notes":"Communication, preuves, suivi médical."},
{"id":95,"cluster":"Expérience & service","titre":"Indicateurs clés à suivre sur son contrat","mot_cle_principal":"indicateurs clés contrat assurance emprunteur","intention":"informationnelle","type_evergreen":"liste","notes":"Coût total, garanties actives, exclusions, délais."},

# 20. FAQ & idées reçues (5)
{"id":96,"cluster":"FAQ & idées reçues","titre":"10 idées reçues sur l’assurance emprunteur","mot_cle_principal":"idées reçues assurance emprunteur","intention":"informationnelle","type_evergreen":"myth‑busting","notes":"Démonter mythes courants sans attaquer d’acteurs."},
{"id":97,"cluster":"FAQ & idées reçues","titre":"L’assurance emprunteur est‑elle obligatoire pour tous les prêts ?","mot_cle_principal":"assurance emprunteur obligatoire tous prêts","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Différencier immobilier vs conso; rester général."},
{"id":98,"cluster":"FAQ & idées reçues","titre":"Changer d’assurance fait‑il toujours baisser le TAEG ?","mot_cle_principal":"changer assurance emprunteur taeg baisse","intention":"informationnelle","type_evergreen":"myth‑busting","notes":"Expliquer cas où l’impact est limité."},
{"id":99,"cluster":"FAQ & idées reçues","titre":"La banque peut‑elle refuser une délégation d’assurance ?","mot_cle_principal":"banque refuser délégation assurance emprunteur","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Équivalence et justification; rester non‑juridique."},
{"id":100,"cluster":"FAQ & idées reçues","titre":"Assurance emprunteur et co‑emprunteurs : qui paie quoi ?","mot_cle_principal":"assurance emprunteur coemprunteurs qui paie","intention":"informationnelle","type_evergreen":"fondamentaux","notes":"Lien quotité/indemnisation; exemples génériques."},
]

df = pd.DataFrame(themes)
csv_path = "data/themes_assurance_emprunteur_100_fr.csv"
df.to_csv(csv_path, index=False)
print(csv_path)
